### ISSUE TITLE
More information on how to use the plugin

### ISSUE THREAD

**Issue by mudrd8mz** [fschuett/moodle-enrol_oss#2]
I can't find more detailed information on how to use and configure the plugin. Is there a manual / documentation available somewhere on how to use this enrolment plugin? I can only see a list of declared features in the description. But what I am supposed to do if, for example, I need to make "Automatic creation/deletion of course categories for teachers." happen?

This should be more clear to the plugin page visitors.

**Comment by fschuett** [comment]
I was awaiting approval of my plugin and would like to provide this information on the moodle plugin documentation pages. I want to process the bugs in moodle bug tracking as well, but I can do so only after it is approved. Meanwhile I added an external documentation page to github.

https://github.com/fschuett/moodle-enrol_oss/wiki/Usage

**Comment by mudrd8mz** [comment]
Well, I don't think we need to wait for the plugin approval do we?

**Comment by mudrd8mz** [comment]
In either case, thanks for providing more info.

**Comment by fschuett** [comment]
No, I don't think so, I will add the information. I was not aware to be able to.
