### ISSUE TITLE
Classes like parent_filtering should be namespaced

### ISSUE THREAD

**Issue by mudrd8mz** [fschuett/moodle-enrol_oss#3]
Ref: https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

**Comment by fschuett** [comment]
I renamed the classes, which were not properly named. I did not rename tasks, since in my understanding they are referenced with their path name, please correct me if I'm wrong.

**Comment by fschuett** [comment]
Well actually I need to move the classes to the classes directory and use namespaces.

**Comment by mudrd8mz** [comment]
> I did not rename tasks

Correct. Because the tasks classes such as `enrol_oss\task\sync_classes_task` are correctly namespaced as per https://docs.moodle.org/dev/Coding_style#Namespaces 

The problem was with classes in the global space.

**Comment by fschuett** [comment]
I namespaced classes and moved them to classes/parents for automatic class loading to take over.
